package dev.codex.pyscriptmod.script.ir;

public enum OpCode {
    LOAD_CONST,
    LOAD_NAME,
    STORE_NAME,
    POP,
    UNARY_NEGATE,
    UNARY_NOT,
    BINARY_ADD,
    BINARY_SUB,
    BINARY_MUL,
    BINARY_DIV,
    BINARY_MOD,
    BINARY_EQ,
    BINARY_NE,
    BINARY_LT,
    BINARY_LE,
    BINARY_GT,
    BINARY_GE,
    BINARY_AND,
    BINARY_OR,
    CALL,
    BUILD_LIST,
    BUILD_DICT,
    GET_INDEX,
    GET_ATTR,
    JUMP,
    JUMP_IF_FALSE,
    MAKE_FUNCTION,
    REGISTER_EVENT,
    IMPORT_MODULE,
    GET_ITER,
    FOR_ITER,
    RETURN
}
